### ISSUE TITLE
apache urlrewrite not working

### ISSUE THREAD

**Issue by jodijunan** [atsanna/codeigniter4-docker#1]
Hi,
First of all, thank you very much for this docker image. It gets me on codeigniter4 on macbook in only a few hours.
I have 1 suggestion for improvement. Currently the mod rewrite is not enable the .htaccess does not work (at least in my installation). I needed to ssh into the docker and run "a2enmod rewrite" and restart the apache to get the rewrite working.
Maybe can add a line in Dockerfile:
RUN a2enmod rewrite

Just in case you are interested, I have also map apache.conf and startScript.sh to local directory.

Again, thank you for this project. Great job!

**Comment by atsanna** [comment]
Hi.
Thanks a lot for your report.
As required, I added the "RUN a2enmod rewrite" line in Dockerfile
Enjoy
