### ISSUE TITLE
database

### ISSUE THREAD

**Issue by fakriardian** [atsanna/codeigniter4-docker#12]
hi atsanna, what is credentials from phpmyadmin and database ?

**Comment by atsanna** [comment]
Hello Fakriardian,
the username is root, the password is the one set in the docker-compose.yml file [MYSQL_ROOT_PASSWORD]

**Comment by atsanna** [comment]
Hello Fakriardian,

The credentials for the database are set in the docker-compose.yml file

          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: codeigniter4
          MYSQL_USER: codeigniter4
          MYSQL_PASSWORD: codeigniter4

For phpmyadmin, if you log in with the root user the password is the one set in the MYSQL_ROOT_PASSWORD variable, otherwise you can use the values ​​of the MYSQL_USER and MYSQL_PASSWORD variables.

I hope I have helped you.

**Comment by fakriardian** [comment]
I think the problem is here
![image](https://user-images.githubusercontent.com/27075371/97812220-6f2e6500-1cb2-11eb-847d-7fa1e077b2ea.png)
when I check the logs from image mariadb:10.5.5, The logs is here
![image](https://user-images.githubusercontent.com/27075371/97812293-f11e8e00-1cb2-11eb-80a4-237b8d706ca3.png)



> Hello Fakriardian,
> 
> The credentials for the database are set in the docker-compose.yml file
> 
> ```
>       MYSQL_ROOT_PASSWORD: rootpassword
>       MYSQL_DATABASE: codeigniter4
>       MYSQL_USER: codeigniter4
>       MYSQL_PASSWORD: codeigniter4
> ```
> 
> For phpmyadmin, if you log in with the root user the password is the one set in the MYSQL_ROOT_PASSWORD variable, otherwise you can use the values ​​of the MYSQL_USER and MYSQL_PASSWORD variables.
> 
> I hope I have helped you.

**Comment by fakriardian** [comment]
Hi atsanna,

The problem is solved, just need use named volumes to codeigniter4_msysql.

_https://stackoverflow.com/questions/40109596/docker-mariadb-mysql-startup-fails-on-windows-host_
