### ISSUE TITLE
Cant change apache document root

### ISSUE THREAD

**Issue by pepitnow** [atsanna/codeigniter4-docker#16]
Hi ! Congratulations on your project. I find it great. I am new to Docker and this solves many problems! 
I would like to know how to change apache Documentroot to /var/ww/html 
I tried many different ways and I can not get it changed I have always Codeigniter 4..1.1 starting at locahost.
I need to run different instances and diferent projects on localhost that's why I need to change it, but no way!
Can you please help me ?
Thank you and congratulatins again!
Paul

**Comment by atsanna** [comment]
Hi !
I am glad that the project solves your problems.

The apache configuration is located in the apache.conf file, inside the conf folder.

Hope the answer can solve your needs.

Antonio

**Comment by pepitnow** [comment]
Thank you for your reply Antonio. I was changing the file as yopu mentioned in your reply but I could not see the changes. 
I was changing the Dockerfile, recretaing the images but in the .yml file the container was taking the image from the reposiry.
That is the reason why I as not able to see my changes. I was helped by a friend who is a master on Docker, and of course I am very newbie.
Thank you for your time and support and contnue the nice work!
Paul
