### ISSUE TITLE
Apache2 not starting on container start?

### ISSUE THREAD

**Issue by Humancell** [atsanna/codeigniter4-docker#17]
Hello,

Thank you for creating this image ... it's great!  I do have one issue ... Apache2 is not starting when I launch the container.  I've been trying to dig for logs or any way to debug this, but I can't find anything.  dmesg fails, etc.

Any ideas on why?

Each time I launch the container I have to issue a "service apache2 restart" and then everything is ok.

**Comment by atsanna** [comment]
Hi, thank you for this report.

Could you specify the operating system where you installed docker?

Thank you

**Comment by Humancell** [comment]
Hello,

It's on two different machines, and I just realized they are both OS-X machines.  One is an iMac (Mojave) and the other is a MacBook.  I haven't tested on other platforms.  Latest Docker Desktop on both.

**Comment by atsanna** [comment]
Unfortunately I don't have a mac to do a test
I have seen that in the past there was a similar problem with Windows that could be solved in this way
https://github.com/atsanna/codeigniter4-docker/commit/076e248f9a3d7d0ea1a3275f4eac1cab0313074f

For some reason this modification was lost and I need to restore it.

Try replacing line 35 in the Dockerfile
from so
ADD startScript.sh /startScript.sh
to so
RUN printf "#!/bin/bash\nmv /codeigniter4 /var/www/html\n/usr/sbin/apache2ctl -D FOREGROUND" > /startScript.sh

build the image
docker build . -t codeigniter:4.1.1

and start the container
docker container run --publish 80:80 --name ci4 -v /localfolder:/var/www/html codeigniter:4.1.1

**Comment by Humancell** [comment]
Hello,

This is strange, but the file was there, and appears to be the correct contents.

root@e546834a0bac:/var/www/html# cat /startScript.sh 
#!/bin/bash
mv /codeigniter4 /var/www/html
/usr/sbin/apache2ctl -D FOREGROUND
root@e546834a0bac:/var/www/html#

I added an extra "\n" at the end to test that also.  But it still is not working.

Any other ideas?

**Comment by Humancell** [comment]
Also, I'm not sure if this helps, but when I tried to manually run the command, i got this output:

```
root@e546834a0bac:/var/www/html# /usr/sbin/apache2ctl -D FOREGROUND
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Fri Apr 30 14:51:02.991322 2021] [core:warn] [pid 66] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 30 14:51:02.997759 2021] [mpm_prefork:notice] [pid 66] AH00163: Apache/2.4.38 (Debian) PHP/7.3.27 configured -- resuming normal operations
[Fri Apr 30 14:51:02.997787 2021] [core:notice] [pid 66] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```
