### ISSUE TITLE
Unable to connect to the database. 

### ISSUE THREAD

**Issue by silanet** [atsanna/codeigniter4-docker#6]
Hi, thank you for your work.
I created and started the containers on both a mac book pro and windows but codeigniter gives the error "Unable to connect to the database." while phpmyadmin container works fine.

in Database.php I tried both with 'hostname' => 'codeigniter4_mysql', and with 'hostname' => 'localhost'.

Can you help me?

Thank you

**Comment by atsanna** [comment]
Hello.
Thank you very much for your report.
With the latest update, I forgot to install and enable the php extension for mysql

I invite you to update the **atsanna/codeigniter4:v4.0.4.1 ** image (the latest is in progress on hub.docker.com)
I also changed mysql in favor of mariadb (see **docker-compose.yml**)
You should now be able to connect the database without any problems

This is the configuration of my Database.php

	public $default = [
		'DSN'      => '',
		'hostname' => 'codeigniter4_mysql',
		'username' => 'codeigniter4',
		'password' => 'codeigniter4',
		'database' => 'codeigniter4',
		'DBDriver' => 'MySQLi',
		'DBPrefix' => '',
		'pConnect' => false,
		'DBDebug'  => (ENVIRONMENT !== 'production'),
		'cacheOn'  => false,
		'cacheDir' => '',
		'charset'  => 'utf8',
		'DBCollat' => 'utf8_general_ci',
		'swapPre'  => '',
		'encrypt'  => false,
		'compress' => false,
		'strictOn' => false,
		'failover' => [],
		'port'     => 3306,
	];

this is my test to create a table

		$fields = [
			'id'          => [
					'type'           => 'INT',
					'constraint'     => 5,
					'unsigned'       => true,
					'auto_increment' => true
			],
			'title'       => [
					'type'           => 'VARCHAR',
					'constraint'     => '100',
					'unique'         => true,
			],
			'author'      => [
					'type'           =>'VARCHAR',
					'constraint'     => 100,
					'default'        => 'King of Town',
			],
			'description' => [
					'type'           => 'TEXT',
					'null'           => true,
			],
			'status'      => [
					'type'           => 'ENUM',
					'constraint'     => ['publish', 'pending', 'draft'],
					'default'        => 'pending',
			],
		];
		$forge = \Config\Database::forge();
		$forge->addField($fields);
		$forge->addPrimaryKey('id');
		$forge->addUniqueKey(['id']);

		$forge->createTable('test');
		dd($forge);

**Comment by silanet** [comment]
Thank you. Now works.

Grazie.
